### ISSUE TITLE
migrate application from SQL database to NoSQL database

### ISSUE THREAD

**Issue by Japoivvb** [Oscarg4/Hibernate#6]
1. modify application to use only mongoDB, remove Hibernate(MySQL) sentence once everything is working

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot(from each collection) in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by Oscarg4** [comment]
![image](https://github.com/Oscarg4/Hibernate/assets/146353899/61ab2574-158e-4344-824e-ed9fa1dad0c4)
![image](https://github.com/Oscarg4/Hibernate/assets/146353899/2006654f-cb50-442d-9450-4688bee57d00)
![image](https://github.com/Oscarg4/Hibernate/assets/146353899/cb34a5e6-3841-463f-9df8-e14853f687b5)
![image](https://github.com/Oscarg4/Hibernate/assets/146353899/2421a8e8-5028-42ce-a05b-074b37fb2f41)

**Comment by Japoivvb** [comment]
1. ok
2. ko
3. ok
4. ok
5. ok
